version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - form-builder-developers
  - brenetic
  ignore:
  - dependency-name: redoc-cli
    versions:
    - 0.11.1
  - dependency-name: "@redocly/openapi-cli"
    versions:
    - 1.0.0-beta.33
    - 1.0.0-beta.39
    - 1.0.0-beta.41
